#!/usr/bin/env python3
"""
Render ASSETS.md from assets/credits.json.

The audio and image fetchers each record provenance for every file they write.
This turns that into the attribution document the licenses actually require --
CC BY and CC BY-SA both oblige us to credit the author and name the license,
and CC BY-SA additionally binds those files to share-alike terms.

Run after generate_sounds.py or fetch_visuals.py:

    python build_assets_doc.py
"""

import collections
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
CREDITS = os.path.join(ROOT, "assets", "credits.json")
OUTPUT = os.path.join(ROOT, "ASSETS.md")

HEADER = """# Asset credits

The source code of Toddler Mode is MIT licensed (see `LICENSE`). The files
under `assets/` are **not** -- they are third-party works redistributed under
their own terms, listed below.

Several carry obligations that MIT does not:

- **CC BY-SA** requires attribution *and* is share-alike: if you redistribute
  these audio files, modified or not, they stay under CC BY-SA.
- **CC BY** requires attribution.
- **Apache-2.0** requires the license notice be preserved.

This file is generated by `build_assets_doc.py`. Do not edit it by hand --
regenerate it whenever assets are re-fetched.
"""


def _group(entries):
    """Group credit records by (source, license, author-ish)."""
    groups = collections.defaultdict(list)
    for path, meta in sorted(entries.items()):
        key = (meta.get("source", "unknown"), meta.get("license", "unknown"))
        groups[key].append((path, meta))
    return groups


def _section(title, entries, show_authors):
    if not entries:
        return []
    lines = [f"\n## {title}\n"]
    for (source, license_name), items in sorted(_group(entries).items()):
        lines.append(f"\n### {source} — {license_name}\n")
        url = next((m.get("url") for _, m in items if m.get("url")), None)
        lic_url = next((m.get("license_url") for _, m in items if m.get("license_url")), None)
        if url:
            lines.append(f"Source: <{url}>  ")
        if lic_url:
            lines.append(f"License: <{lic_url}>  ")
        lines.append(f"\n{len(items)} file(s).\n")

        if show_authors:
            # Credit each distinct author once, listing what they contributed.
            by_author = collections.defaultdict(list)
            for path, meta in items:
                by_author[meta.get("author", "unknown")].append((path, meta))
            lines.append("| Author | Files | Source page |")
            lines.append("| --- | --- | --- |")
            for author, works in sorted(by_author.items()):
                names = ", ".join(
                    os.path.basename(p).rsplit(".", 1)[0] for p, _ in works[:8]
                )
                if len(works) > 8:
                    names += f", +{len(works) - 8} more"
                page = works[0][1].get("page", "")
                page_cell = f"[file]({page})" if page else ""
                lines.append(f"| {author} | {names} | {page_cell} |")
            lines.append("")
        else:
            voices = sorted({m.get("voice", "") for _, m in items if m.get("voice")})
            if voices:
                lines.append(f"Voice: `{', '.join(voices)}`\n")
    return lines


def main():
    if not os.path.exists(CREDITS):
        raise SystemExit(f"No credits file at {CREDITS}; run the fetchers first.")
    with open(CREDITS) as fh:
        credits = json.load(fh)

    audio = credits.get("audio", {})
    images = credits.get("images", {})
    human = {k: v for k, v in audio.items() if not v.get("generated")}
    synth = {k: v for k, v in audio.items() if v.get("generated")}

    lines = [HEADER]
    lines.append("\n## Summary\n")
    lines.append("| Category | Files |")
    lines.append("| --- | --- |")
    lines.append(f"| Human voice recordings | {len(human)} |")
    lines.append(f"| Synthesised speech | {len(synth)} |")
    lines.append(f"| Images | {len(images)} |")
    lines.append("")

    lines += _section("Audio — human recordings", human, show_authors=True)
    lines += _section("Audio — synthesised", synth, show_authors=False)
    lines += _section("Images", images, show_authors=False)

    lines.append("\n---\n")
    lines.append("Regenerate with `python build_assets_doc.py`.\n")

    with open(OUTPUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {OUTPUT}: {len(human)} human, {len(synth)} synthesised, "
          f"{len(images)} images")


if __name__ == "__main__":
    main()
